using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CoreApi.Common.Models
{
    public enum ErrorDetails
    {
        unAuthorizeuser = 802,
        useralreadylogged = 804,

        DuplicateGaaName = 805,
        InternalServerError = 800,
        MandatoryField = 806,
        MobileComponentName = 807,
        ServiceName = 808,
        JobName = 809,
        ActivityName = 810,
        FromSanctionedLoad = 811,
        ToSanctionedLoad = 812,
        InventoryComponentTypeName = 813,
        StoreItemCategoryName = 814,
        StoreItemName = 815,
        ItemInstallationLocationName = 816,
        IsMandatoryItem = 817,
        IsFromInventory = 818,
        IsMultipleEntry = 819,
        MinQuantityPerItem = 820,
        MaxQuantityPerItem = 821,
        InsertUpdateJobItemKitMaster = 822,
        SaveConfigReadingMaster = 823,
        InsertUpdateJobTypeMaster = 824,
        InsertSystemJobCreation = 825,
        InsertUpdateJobCreation = 826,
        InsertUpdateJobWiseComponentData = 827,
        SaveProjectConfigurations = 828,
        ImportProjectConfigurations = 829,
        DeleteInventoryConfigDetail = 830,
        InsertUpdateInventoryConfig = 831,
        InsertUpdateGaaDetailAdd = 832,
        InsertUpdateGaaDetailUpdate = 833,
        InsertUpdateGaaDetailDelete = 834,
        InsertUpdateRoleMasterAdd = 835,
        InsertUpdateRoleMasterUpdate = 836,
        InsertUpdateRoleMasterDelete = 837,
        StartDateParameter = 838,
        EndDateParameter = 839,
        JobCode = 840,
        DateOfEffect = 841,
        QuantityParameter = 842,
        IsDefaultConsume = 843,
        ServiceCode = 844,
        IsStandAlone = 845,
        GaaName = 846,
        GaaLevel = 847,
        GaaCode = 848,
        GaaParentId = 849,
        ProjectNumber = 850,
        PurchaseOrderNumber = 851,
        PurchaseOrderDate = 852,
        CustomerName = 853,
        ProjectName = 854,
        ProjectDescription = 855,
        KDFUtilityCode = 856,
        SPVCode = 857,
        DuplicateServiceName = 858,
        AllowActivityType = 859,
        ServicePriority = 860,
        InsertUpdateGlobalParameterAdd = 861,
        InsertUpdateFTPConfigAdd = 862,
        InsertUpdateBuyerMasterAdd = 863,
        InsertUpdateBuyerMasterDelete = 864,
        InsertUpdateBuyerMasterUpdate = 865,
        InsertUpdateStoreCreation = 866,
        InsertUpdateStockCategoryCreation = 867,
        approveStockoutDetails = 868,
        StockItemTemplate = 869,
        insertUpdateRemovedItem = 870,
        StockItemIn = 871,
        ProjectHierarchyRole = 872,
        RoleName = 873,
        insertFileMaster = 874,
        insertUpdateProductMaster = 875,
        updateProductKeyMapping = 876,
        DuplicateProjectName = 877,
        DuplicateServiceCode = 878,
        ChangePassword = 879,
        InsertUpdateSumoMasterDelete = 880,
        blankApiEndPoint = 881,
        blankSupplierCode = 882,
        blankUserName = 883,
        blankPs = 884,
        DuplicateActivityName = 885,
        insertUpdateActivityMaster = 886,
        Invalidtoken = 887,
        Invaliduserid = 888,
        Invaliddatecriteria = 889,
        Invalidproductid = 890,
        Invalidclientid = 891,
        Noinputfile = 892,
        Invalidrequest = 893,
        Itemkitforselectedjobisnotavailable = 894,
        Notrackingfoundforsearcheditem = 895,
        AssignJobMsg = 896,
        SaveStockOut = 897,
        MeterReadingData = 898,
        ConsumerDetail = 899,
        InsertUpdateConsumerMasterInsert = 900,
        InsertUpdateConsumerMasterUpdate = 901,
        SendJobToUnassign = 902,
        GaaDataDetail = 903,
        GaaDataLevelIdDetail = 904,
        GaaDataSourceGaaId = 905,
        #region Job Management

        EnumNotInRange = 906,
        EmptyMandatoryField = 907,
        InvalidDate = 908,
        SizeOverflow = 909,
        InvalidJobWiseRequestParamFormat = 910,
        Postgres = 911,
        InvalidIdorSPVCode = 912,
        UnknownExceptionError = 1001,

        #endregion

    }
}
